FROM node:lts
WORKDIR /app

COPY backend/package*.json ./
COPY backend/package-lock.json backend/package-lock.json

RUN npm install

COPY backend  ./backend

WORKDIR /app/backend

ARG DATABASE_URL=postgresql://dummy:dummy@localhost:5432/dummy
ENV DATABASE_URL=$DATABASE_URL

RUN npx prisma generate

RUN npm run build


EXPOSE 3000

CMD ["sh", "-c", "npx prisma generate && npx prisma migrate deploy && npm run start"]