FROM node:lts
WORKDIR /app

COPY backend/package*.json ./
COPY backend/package-lock.json backend/package-lock.json

RUN npm install

COPY backend  ./backend

WORKDIR /app/backend



RUN npx prisma generate 
RUN npm run build


EXPOSE 3000

CMD [ "npm", "run", "start" ]